apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubepulse.fullname" . }}-frontend
  labels:
    {{- include "kubepulse.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kubepulse.name" . }}-frontend
