apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: kubepulse
type: Opaque
stringData:
  mongo-root-username: admin
  mongo-root-password: ProductionSecurePass2026!
  mongo-database: kubepulse
